### PR TITLE
Allow setCategory to be called statically on iOS

### PR DESCRIPTION
**Pull request by mattvot**

### CODE REVIEW

**Comment by benvium** [comment]
@mattvot Can you update the readme too? should be a trivial change

**Comment by mattvot** [comment]
Ah yep, and the version number too

**Comment by mattvot** [comment]
The README already has the correct argument documented. There's another static method `enableInSilenceMode` also documented but does not describe that it is called statically.

**Comment by benvium** [comment]
@mattvot Great - thanks for checking. Let's merge this! Can you do the release to npm please?

**Comment by mattvot** [comment]
Will do

**Pull request merged**
